# Generated by Django 4.2 on 2024-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Мужской", "Мужской"), ("Женский", "Женский")], max_length=50, verbose_name="Пол"
            ),
        ),
    ]
