# Generated by Django 4.2 on 2024-05-31 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("Онлайн", "Онлайн"), ("Оффлайн", "Оффлайн")], default="Оффлайн", max_length=50
            ),
        ),
    ]
