# Generated by Django 4.2 on 2024-06-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_activity_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/profile/", verbose_name="Аватар"),
        ),
    ]
