version: "3.9"

services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    command: make runserver
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: dev
    container_name: celery-worker
    command: make celery-worker
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: dev
    container_name: celery-beat
    command: make celery-beat
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

volumes:
  postgres_data: